branches:
  only:
  - master
  - develop

sudo: false

addons:
  apt:
    packages:
      - vim

branches:
  only:
    - master
    - travis

install:
  # Install vim plugins
  - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - cp .travis/vimrc ~/.vimrc
  - vim -u ~/.vimrc +PlugInstall +qall

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

script:
  - vim --version
  - python --version
  - python ./vim-plugins-profile.py vim -u NONE
  - python ./vim-plugins-profile.py vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -n 5 vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -n 5 -r 10 vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -s vim -N -u NORC
